# Site settings
title: g4idrijs的技术博客
email: g4idrijs@gmail.com
description: > #g4idrijs的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: " " # the base hostname & protocol for your site
twitter_username: g4idrijs
github_username:  g4idrijs

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: g4idrijs
  email: g4idrijs@sina.com
  link: http://liuyanwei.jumppo.com/
  weibo: http://weibo.com/1897719834
  github: http://github.com/coolnameismy
title: g4idrijs的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器
